Map:   0%|          | 0/15 [00:00<?, ? examples/s]Map: 100%|██████████| 15/15 [00:00<00:00, 137.80 examples/s]                                                            Map:   0%|          | 0/5 [00:00<?, ? examples/s]                                                 Map (num_proc=6):   0%|          | 0/15 [00:00<?, ? examples/s]Map (num_proc=6):   7%|▋         | 1/15 [00:00<00:04,  2.96 examples/s]Map (num_proc=6):  27%|██▋       | 4/15 [00:00<00:01,  8.39 examples/s]Map (num_proc=6):  47%|████▋     | 7/15 [00:00<00:00, 10.01 examples/s]Map (num_proc=6):  67%|██████▋   | 10/15 [00:01<00:00, 10.82 examples/s]Map (num_proc=6):  93%|█████████▎| 14/15 [00:01<00:00, 12.40 examples/s]                                                                        Map (num_proc=5):   0%|          | 0/5 [00:00<?, ? examples/s]Map (num_proc=5):  20%|██        | 1/5 [00:00<00:00,  4.62 examples/s]Map (num_proc=5):  40%|████      | 2/5 [00:00<00:00,  6.22 examples/s]Map (num_proc=5):  60%|██████    | 3/5 [00:00<00:00,  7.51 examples/s]Map (num_proc=5):  80%|████████  | 4/5 [00:00<00:00,  7.85 examples/s]Map (num_proc=5): 100%|██████████| 5/5 [00:00<00:00,  8.36 examples/s]                                                                      /scratch/work/lunt1/.conda_envs/w2v2/lib/python3.11/site-packages/transformers/optimization.py:391: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
Traceback (most recent call last):
  File "/scratch/work/lunt1/wav2vec2-finetune/finetune.py", line 340, in <module>
    run_train(i, processor, model, train_dataset, val_dataset, training_args)
  File "/scratch/work/lunt1/wav2vec2-finetune/finetune.py", line 256, in run_train
    loss = model(input_values=batch.input_values.squeeze(0), 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/work/lunt1/.conda_envs/w2v2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/work/lunt1/.conda_envs/w2v2/lib/python3.11/site-packages/accelerate/utils/operations.py", line 553, in forward
    return model_forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/work/lunt1/.conda_envs/w2v2/lib/python3.11/site-packages/accelerate/utils/operations.py", line 541, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/work/lunt1/.conda_envs/w2v2/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/work/lunt1/.conda_envs/w2v2/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1139, in forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 0: 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 330 331 332 333 334 335 336 337 338 339 340 341 342 343 344 345
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 12011) of binary: /scratch/work/lunt1/.conda_envs/w2v2/bin/python
Traceback (most recent call last):
  File "/scratch/work/lunt1/.conda_envs/w2v2/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/work/lunt1/.conda_envs/w2v2/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/scratch/work/lunt1/.conda_envs/w2v2/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/scratch/work/lunt1/.conda_envs/w2v2/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/scratch/work/lunt1/.conda_envs/w2v2/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/work/lunt1/.conda_envs/w2v2/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-27_09:33:02
  host      : gpu26.int.triton.aalto.fi
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 12011)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: gpu26: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=19621699.0
